import type {Item, Result} from 'src/types/mbti';

export const results: Result[] = [
  {key: 'ENFP', imageSrc: require('../assets/icons/ENFP.png')},
  {key: 'ENFJ', imageSrc: require('../assets/icons/ENFJ.png')},
  {key: 'INFP', imageSrc: require('../assets/icons/INFP.png')},
  {key: 'INFJ', imageSrc: require('../assets/icons/INFJ.png')},
  {key: 'ESFP', imageSrc: require('../assets/icons/ESFP.png')},
  {key: 'ESFJ', imageSrc: require('../assets/icons/ESFJ.png')},
  {key: 'ISFP', imageSrc: require('../assets/icons/ISFP.png')},
  {key: 'ISFJ', imageSrc: require('../assets/icons/ISFJ.png')},
  {key: 'ENTJ', imageSrc: require('../assets/icons/ENTJ.png')},
  {key: 'ESTJ', imageSrc: require('../assets/icons/ESTJ.png')},
  {key: 'INTP', imageSrc: require('../assets/icons/INTP.png')},
  {key: 'ISTJ', imageSrc: require('../assets/icons/ISTJ.png')},
  {key: 'ESTP', imageSrc: require('../assets/icons/ESTP.png')},
  {key: 'ESFP', imageSrc: require('../assets/icons/ESFP.png')},
  {key: 'ISTP', imageSrc: require('../assets/icons/ISTP.png')},
  {key: 'ISFP', imageSrc: require('../assets/icons/ISFP.png')},
];

export const items: Item[] = [
  {
    key: 'E',
    title: '외향형',
    caption: '사교적이며 활동적인',
    type: 'M',
    bgcolor: '#76B0F1',
    color: '#103996',
    selected: false,
  },
  {
    key: 'I',
    title: '내향형',
    caption: '깊이있는 대인관계',
    type: 'M',
    bgcolor: '#76B0F1',
    color: '#103996',
    selected: false,
  },
  {
    key: 'S',
    title: '감각형',
    caption: '오감에 의존하나 철저한',
    type: 'B',
    bgcolor: '#FFA48D',
    color: '#B72136',
    selected: false,
  },
  {
    key: 'N',
    title: '직관형',
    caption: '영감에 의존하며 신속한',
    type: 'B',
    bgcolor: '#FFA48D',
    color: '#B72136',
    selected: false,
  },
  {
    key: 'T',
    title: '사고형',
    caption: '분석적이며 논리적인',
    type: 'T',
    bgcolor: '#FFE16A',
    color: '#B78103',
    selected: false,
  },
  {
    key: 'F',
    title: '감정형',
    caption: '사람관계에 관심 갖는',
    type: 'T',
    bgcolor: '#FFE16A',
    color: '#B78103',
    selected: false,
  },
  {
    key: 'J',
    title: '판단형',
    caption: '철저하고 계획적인',
    type: 'I',
    bgcolor: '#84A9FF',
    color: '#1939B7',
    selected: false,
  },
  {
    key: 'P',
    title: '인식형',
    caption: '자율적이고 융통성 있는',
    type: 'I',
    bgcolor: '#84A9FF',
    color: '#1939B7',
    selected: false,
  },
];
